### ISSUE TITLE
Can't change background

### ISSUE THREAD

**Issue by logological** [miguelsimoni/hugo-initio#26]
The `config.toml` contains a `background` parameter which seems to be for controlling the background image on the main page.  However, as far as I can tell this parameter is never used by the template.  Instead, the CSS is hard-coded to always use `images/bg_head.jpg`.

Please consider changing the template so that it gets the image background from the `background` parameter.

**Comment by moondra2017** [comment]
> The `config.toml` contains a `background` parameter which seems to be for controlling the background image on the main page. However, as far as I can tell this parameter is never used by the template. Instead, the CSS is hard-coded to always use `images/bg_head.jpg`.
> 
> Please consider changing the template so that it gets the image background from the `background` parameter.

So this`"images/guy.jpg"` is also hard-coded?
I can't seem to find an images folder wit this image.

**Comment by mhungerford** [comment]
I opened PR #28: https://github.com/miguelsimoni/hugo-initio/pull/28
That solves this.  

Issue is that hugo cannot configure CSS, and that is where backgrounds to elements are provided.  Fixed by doing just the path as inline CSS in the html, so it could be configured by hugo.
 <div class="banner" style="background-image:url({{ .Site.BaseURL }}{{ .Site.Params.banner }});" >

**Comment by dbryar** [comment]
This PR appears to break the parallax on new install. The banner is now a fixed image with a 90px margin top/bottom, and does not slide with page scroll
